### ISSUE TITLE
UI - Clear filters button

### ISSUE THREAD

**Issue by mmnoo** [sparkgeo/cif-urban-forest-webapp#15]
**Updates:**

- [x] Update type sizing to typography/body2 style: 14px 
- [x] Update typeface to roboto 
- [x] Increase size of icon should be 16x16px
- [x] Add 32px of padding to the top of the clear filters button, text when expanded is quite close (see img below)

**Comment by e-e-james** [comment]
Looks good @mmnoo can we update 

- [ ] type sizing to typography/body1 style: 16px 
- [ ] Update typeface to roboto 
- [ ] Increase size of icon should be 16x16px

**Comment by e-e-james** [comment]
![Image](https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115577613/d9269809-f9a1-4542-8e97-8564f70bec35)

**Comment by ukhan-sg** [comment]
@e-e-james 
<img width="350" alt="image" src="https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115191672/c50e3297-616b-475e-a4d4-d472ab2405fc">

**Comment by ukhan-sg** [comment]
Updated.

1. Default state:
<img width="336" alt="image" src="https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115191672/110a94c7-a7a9-49b6-9806-e8cc37699143">


2. Hover state:
<img width="356" alt="image" src="https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115191672/171e50ef-5734-44ec-a6fa-a5ea19aa3f7a">
