### ISSUE TITLE
UI - Links Revisions

### ISSUE THREAD

**Issue by e-e-james** [sparkgeo/cif-urban-forest-webapp#42]
**Client Note:**
Thank you for letting us know. We understand wanting to maximize the space allotted for the map itself, if the suggested placement for the links to the pages is at the bottom then that should work, however we are wondering if there is a way to make them more visible? We found that they were a bit hard to spot.

**Comment by ukhan-sg** [comment]
Requirements here TBD.

**Comment by e-e-james** [comment]
@ukhan-sg can we update the link text to text/primary: 000000 at 87% for the buttons in the image below 


![Image](https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115577613/207d2ec5-8683-490f-a8cf-c721da3a726d)
