### ISSUE TITLE
UI - Ability to download .shp file

### ISSUE THREAD

**Issue by e-e-james** [sparkgeo/cif-urban-forest-webapp#51]
We need to add in the functionality for a user to download a .shp file I don't think this has been implemented yet?

@ukhan-sg @jonhealy1

**Comment by e-e-james** [comment]
![Image](https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115577613/e64502a2-c978-409b-bba4-b26ca1caf9ea)

**Comment by jonhealy1** [comment]
@ukhan-sg This is working - https://5p9hyrnb5a.execute-api.us-east-1.amazonaws.com/prod/trees/search?cities=Lethbridge&file=shp
