### ISSUE TITLE
Feature: Download Size

### ISSUE THREAD

**Issue by e-e-james** [sparkgeo/cif-urban-forest-webapp#54]
**The file download limits are** 
csv: 225,000 trees
json: 200,000 trees
shp: 140,000 trees

**Comment by e-e-james** [comment]
![Image](https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115577613/70a9e5dc-fdbc-40e2-90cf-72622c251e57)

**Comment by jonhealy1** [comment]
To fetch the download size it looks like this: https://5p9hyrnb5a.execute-api.us-east-1.amazonaws.com/prod/trees/search?cities=Lethbridge&file_size=shp

**Comment by jonhealy1** [comment]
To download the file and get the file link it looks like this: https://5p9hyrnb5a.execute-api.us-east-1.amazonaws.com/prod/trees/search?cities=Lethbridge&file=shp

**Comment by e-e-james** [comment]
@ukhan-sg is it difficult to have the file size round up to a whole number in this case it would be 1181 MB

![Image](https://github.com/sparkgeo/cif-urban-forest-webapp/assets/115577613/60b0c135-0463-4f48-9f9c-556e99fe2219)

**Comment by ukhan-sg** [comment]
@e-e-james Updated UI to round to next largest whole MB 👍
